### PR TITLE
repo: merge beta into main addon

### LINKED ISSUE #16: Non Qwerty Keyboards have issues with the pre-set binds for the gamemode
dont know how fixable this is but since ive seen it crop up in the discord enough i feel as if it should be put here just incase you figure out a method of fixing it, seems to be that using gmod keycodes ignore keyboard layouts  and instead act as if every keyboard is qwerty (uk/us)

### LINKED ISSUE #28: Points sometimes don't get awarded properly
Even if you meet the conditions for some points end-of-round, you may not get them.

### LINKED ISSUE #29: Trollge stage 3 + speedrunner stage 2 = massive FPS lag
Possibly related to music

### LINKED ISSUE #31: Survivors sometimes respawn when they shouldn't
Usually when the cause of death is not a slasher (prop deaths or limitedzones). Might be due to an error in the death hook, possible that it's not even slashco related?

### LINKED ISSUE #35: Male07 broken [beta-changes tree]
Male07 can't kill workers and can't use ability on button "R"
Console error

Image

### LINKED ISSUE #38: Viewmodel not appearing in hands [beta-changes]
Image

Image

### LINKED ISSUE #42: Slashco hatman do errors on console [beta-changes]
Console log:
sc_hatman[677]:SetAbsOrigin( 131363.296875 16980.404297 -3017.143311 ): Ignoring unreasonable position.
sc_hatman[677]:SetAbsOrigin( 260694.843750 33698.007812 -5911.153809 ): Ignoring unreasonable position.
sc_hatman[677]:SetAbsOrigin( 131115.734375 16948.193359 -2887.450195 ): Ignoring unreasonable position.
sc_hatman[677]:SetAbsOrigin( 131103.843750 16946.652344 -2887.187744 ): Ignoring unreasonable position. (x6)
sc_hatman[677]:SetAbsOrigin( 133916.781250 18191.769531 -68420.437500 ): Ignoring unreasonable position.
sc_hatman[677]:SetAbsOrigin( 266961.187500 36234.191406 -133620.531250 ): Ignoring unreasonable position.
sc_hatman[677]:SetAbsOrigin( 131099.046875 17809.601562 -66741.507812 ): Ignoring unreasonable position.
sc_hatman[677]:SetAbsOrigin( 131088.359375 17808.148438 -66736.250000 ): Ignoring unreasonable position.
sc_hatman[677]:SetAbsOrigin( 131077.671875 17806.695312 -66730.992188 ): Ignoring unreasonable position.
sc_hatman[677]:SetAbsOrigin( 131139.546875 17815.078125 -66720.476562 ): Ignoring unreasonable position.
sc_hatman[677]:SetAbsOrigin( 131128.859375 17813.625000 -66715.218750 ): Ignoring unreasonable position.
sc_hatman[677]:SetAbsOrigin( 131118.171875 17812.171875 -66709.960938 ): Ignoring unreasonable position.
sc_hatman[677]:SetAbsOrigin( 131107.500000 17810.720703 -66704.703125 ): Ignoring unreasonable position.
sc_hatman[677]:SetAbsOrigin( 131096.796875 17809.265625 -66699.445312 ): Ignoring unreasonable position.

### LINKED ISSUE #63: Thirsty bug with animation [beta-changes]
Milk in wrong position
Image

### LINKED ISSUE #66: Abomignat hud bug [beta-changes]
Image
Bug works when you not cancelling crawling(r abillty) on r button. Example: when you jump on crawling you can see this bug

### PR DESCRIPTION
**Pull request by RaphaelIT7**
ToDo:
\- Finish Changelog

### CODE REVIEW

File: gamemodes/slashco/entities/effects/rocks_lightning.lua [hunk 1]
```diff
@@ -0,0 +1,66 @@
...
+
+	// start the beam with 14 points
+	render.StartBeam(14)
+
+	// add start
+	render.AddBeam(
+		start_pos,				// Start position
+		self.BeamSize,					// Width
+		CurTime(),				// Texture coordinate
+		Color(143, 167, 240, 255)		// Color
```
Comment (textstack) [inline gamemodes/slashco/entities/effects/rocks_lightning.lua]: the colors can be cached like the materials; colors are not as memory intensive as materials but can still flood the garbage collector if too many are made/destroyed frequently (same with vectors and angles)

File: gamemodes/slashco/entities/entities/sc_activeteslacoil.lua [hunk 2]
```diff
@@ -0,0 +1,307 @@
...
+		self:DrawModel()
+
+		if noLighting then
+			render.SuppressEngineLighting(false)
+		end
+
+		if state == 4 then
+			local pos = self:GetPos()
+			local mins, maxs = self:GetModelBounds()
+			local centerPos = pos + maxs + Vector(mins[1], mins[2])
```
Comment (textstack) [inline gamemodes/slashco/entities/entities/sc_activeteslacoil.lua]: vectors/angles/colors can be recycled to avoid having to make a new one for dynamic values
```
local vec = Vector()
function Ent:Draw()
    ...
    vec.x, vec.y, vec.z = foo, bar, law
    ...
```

File: gamemodes/slashco/entities/entities/sc_beerkeg.lua [hunk 3]
```diff
@@ -0,0 +1,144 @@
...
+		phys:SetMaterial("gmod_bouncy")
+	end
+
+	self.ExplodeMeter = 0
+end
+
+function ENT:SetBeerKegVelocity(velocity)
+	local phys = self:GetPhysicsObject()
+	if IsValid(phys) then
+		velocity[3] = velocity[3]
```
Comment (textstack) [inline gamemodes/slashco/entities/entities/sc_beerkeg.lua]: this line does nothing

File: gamemodes/slashco/entities/entities/sc_battery.lua [hunk 4]
```diff
@@ -1,8 +1,40 @@
...
+	local curTime = CurTime()
+	self:NextThink(curTime + 0.5)
+
+	if SlashCo.OverTime > SlashCo.GetRoundTime() then
+		return true
+	end
+
+	local nearbyBatteries = 0 -- If multiple fuel cans are nearby, we play sounds more likely to play a sound. Why? Because when Tyler for example decides to make a funny pile, we want everyone to know where it is.
+	local class = self:GetClass()
+	for _, ent in ipairs(ents.FindInSphere(self:GetPos(), 200)) do
```
Comment (textstack) [inline gamemodes/slashco/entities/entities/sc_battery.lua]: Should use ents.FindInBox instead since that does not need to iterate over every entity

File: gamemodes/slashco/entities/entities/sc_gascan.lua [hunk 5]
```diff
@@ -16,4 +16,39 @@ if SERVER then
...
+	local curTime = CurTime()
+	self:NextThink(curTime + 0.5)
+
+	if SlashCo.OverTime > SlashCo.GetRoundTime() then
+		return true
+	end
+
+	local nearbyFuelCans = 0 -- If multiple fuel cans are nearby, we play sounds more likely to play a sound. Why? Because when Tyler for example decides to make a funny pile, we want everyone to know where it is.
+	local class = self:GetClass()
+	for _, ent in ipairs(ents.FindInSphere(self:GetPos(), 200)) do
```
Comment (textstack) [inline gamemodes/slashco/entities/entities/sc_gascan.lua]: same as for batteries, it would be better to use FindInBox

File: gamemodes/slashco/entities/entities/sc_hatman.lua [hunk 6]
```diff
@@ -0,0 +1,331 @@
...
+
+	for _, hatMan in ipairs(GameData.HatMans) do
+		if hatMan:GetTarget() == ply then
+			hatMan:Remove()
+		end
+	end
+end)
+
+local RecursiveFindFuthestArea2
+local function RecursiveFindFuthestArea(area, targetPos, depth, maxDepth, lastMaxDistance)
```
Comment (textstack) [inline gamemodes/slashco/entities/entities/sc_hatman.lua]: furthest

File: gamemodes/slashco/entities/entities/sc_offertable.lua [hunk 7]
```diff
@@ -13,61 +13,62 @@ ENT.Instructions = ""
...
-        else
-            self.Offer:SetModel("")
-            self.Offer:SetColor(color_transparent)
-            self.Offer:SetRenderMode(RENDERMODE_TRANSCOLOR)
-        end
-    end
+	function ENT:Think()
+		if SlashCo.LobbyData.Offering > 0 then
+			self.Offer:SetModel("models/slashco/other/offerings/o_" .. SlashCo.LobbyData.Offering .. ".mdl")
+			self.Offer:SetColor(Color(255, 255, 255, 255))
```
Comment (textstack) [inline gamemodes/slashco/entities/entities/sc_offertable.lua]: `color_white`

File: gamemodes/slashco/entities/entities/sc_porchlight.lua [hunk 8]
```diff
@@ -0,0 +1,311 @@
...
+			if state != 1 then continue end
+
+			local lightTime = porchLight:GetLightStartTime()
+			local time = CurTime() - lightTime
+
+			render.SetMaterial(Material("vgui/white"))
+			for k=30, 1, -1 do
+				local size = math.max(math.pow(time, 1.05) - math.pow(k, 1.7), 1)
+				local sphereSize = math.Clamp(size / 5, 10, 20)
+				render.DrawSphere(porchLight:GetCoilOffset(), size, sphereSize, sphereSize, Color(255, 255, 255, (time / 20 * k / 2)))
```
Comment (textstack) [inline gamemodes/slashco/entities/entities/sc_porchlight.lua]: recyclable color opportunity here, especially since this gets called 30 times a frame

File: gamemodes/slashco/gamemode/documents/cl_documents.lua [hunk 9]
```diff
@@ -0,0 +1,35 @@
...
+			continue
+		end
+
+		local rating = net.ReadUInt(2)
+		SlashCo.Documents[name] = {
+			rating = rating,
+		}
+	end
+
+	print("Received Documents:")
```
Comment (textstack) [inline gamemodes/slashco/gamemode/documents/cl_documents.lua]: prefix with [SLASHCO] perhaps

Comment (textstack) [reply gamemodes/slashco/gamemode/documents/cl_documents.lua]: or maybe remove since this is clientside

File: gamemodes/slashco/gamemode/documents/sh_documents.lua [hunk 10]
```diff
@@ -0,0 +1,38 @@
+AddCSLuaFile()
+
+SlashCoDocuments = SlashCoDocuments or {} -- a table containing all existing documents.
+SlashCoDocumentTypes = SlashCoDocumentTypes or {} -- a table containing all documents split into the different types
+
+function SlashCo.RegisterDocument(table)
+	if SC_LOADEDDOCUMENTS then
+		error("Tried to register an document illegally", 2)
```
Comment (textstack) [inline gamemodes/slashco/gamemode/documents/sh_documents.lua]: a document

File: gamemodes/slashco/gamemode/items/items_init.lua [hunk 11]
```diff
@@ -194,93 +285,78 @@ function PLAYER:ItemFunction2OrElse(funcName, item, fallback, ...)
...
-		SlashCo.SendValue(self, "preItem", item) -- networking on nwvars can be slow, this acts as a backup
-	end
-else
-	SlashCo.PreItem = SlashCo.PreItem or "none"
-
-	hook.Add("scValue_preItem", "SlashCoPreItem", function(item, slot)
-		if not slot then
-			SlashCo.PreItem = item or "none"
+		if not validSlots[slot] then
+			error("Tried to use a invalid item slot! (Got: " .. tostring(slot) .. ", Expected one of: " .. table.concat(validSlots, ", ") .. ")")
```
Comment (textstack) [inline gamemodes/slashco/gamemode/items/items_init.lua]: an invalid

File: gamemodes/slashco/gamemode/ui/cl_pings.lua
Comment (textstack) [inline gamemodes/slashco/gamemode/ui/cl_pings.lua]: colors can be cached, there is one below too

File: gamemodes/slashco/gamemode/ui/cl_roundend_hud.lua [hunk 12]
```diff
@@ -266,7 +242,30 @@ local function nextLine(panel, lines)
 	line:SetFont("OutroFont")
 	line:SetContentAlignment(8)
 	line:SetTall(40)
-	line:SetText(lines[#lines])
+
+	local lineData = lines[#lines]
+	local isMultiLabel = istable(lineData)
+	line:SetText(isMultiLabel and lineData[1] or lineData)
+	if isMultiLabel then
+		line:SetTextColor(Color(0, 0, 0, 0))
```
Comment (textstack) [inline gamemodes/slashco/gamemode/ui/cl_roundend_hud.lua]: `color_transparent`

File: gamemodes/slashco/gamemode/sh_canbeseen.lua [hunk 13]
```diff
@@ -40,6 +40,10 @@ function PLAYER:CanSeeFlashlights()
 	return self:GetNWBool("SlashCoSeeFlashlights", true)
 end
 
+function PLAYER:IsVisible()
```
Comment (textstack) [inline gamemodes/slashco/gamemode/sh_canbeseen.lua:44]: might be confused with the actual function CanBeSeen

File: gamemodes/slashco/gamemode/sh_fog.lua [hunk 14]
```diff
@@ -0,0 +1,284 @@
...
+		if fogType == SlashCo.FogType.PLAYER then
+			fogInfo.entIndex = net.ReadUInt(13)
+		elseif fogType == SlashCo.FogType.TEAM then
+			fogInfo.team = net.ReadUInt(10)
+		end
+
+		GameData.FogData[name] = fogInfo
+	end
+
+	PrintTable(GameData.FogData)
```
Comment (textstack) [inline gamemodes/slashco/gamemode/sh_fog.lua]: seems like a debug print

File: gamemodes/slashco/gamemode/sh_perks.lua [hunk 15]
```diff
@@ -0,0 +1,173 @@
+SlashCo.Perks = SlashCo.Perks or {}
+
+function SlashCo.RegisterPerk(table, perkID)
+	if SC_LOADEDPERKS then
+		error("Tried to register an perk illegally", 2)
```
Comment (textstack) [inline gamemodes/slashco/gamemode/sh_perks.lua]: a perk

File: gamemodes/slashco/gamemode/sv_game_logic.lua [hunk 16]
```diff
@@ -132,57 +122,295 @@ SlashCo.LoadCurRoundData = function()
...
+				SlashCo.AwaitPlayerToSelectSlasher(selectedPly, nil)
 			end
+		end)
+	end
+	slasherSelection = RunSlasherSelection
+	RunSlasherSelection()
+end
+_DoSlasherSelection = DoSlasherSelection
+
+function AskPlayersToBecomeSlasher()
```
Comment (textstack) [inline gamemodes/slashco/gamemode/sv_game_logic.lua]: should either be local or part of the SlashCo table

File: lua/slashco/item/newports.lua [hunk 17]
```diff
@@ -0,0 +1,75 @@
...
+ITEM.Price = 40
+ITEM.Description = "Newports_desc"
+ITEM.CamPos = Vector(150, 0, 0)
+ITEM.IsSpawnable = true
+function ITEM.DisplayColor()
+	return 128, 48, 0, 255
+end
+function ITEM.OnUse(ply) -- Unlike in SlashCo VR, this item will decrease the fog.
+	SlashCo.AudioSystem.PlaySound({
+		soundPath = "slashco/newports_eat.ogg", -- It's so cold that we consider it to be concrete at this point :hehe:
```
Comment (textstack) [inline lua/slashco/item/newports.lua]: comment copied from costco pizza

File: lua/slashco/item/teslacoil.lua [hunk 18]
```diff
@@ -0,0 +1,61 @@
...
+	size = Vector(0.3, 0.3, 0.3),
+	color = color_white,
+	surpresslightning = false,
+	material = "",
+	skin = 0,
+	bodygroup = {}
+}
+
+function ITEM.OnUse(ply)
+	--If the holder of the item is the last one alive and at least one generator has been activated, the rescue helicopter will come prematurely.
```
Comment (textstack) [inline lua/slashco/item/teslacoil.lua]: comment copied from beacon

File: lua/slashco/lang/en.lua [hunk 19]
```diff
@@ -532,6 +573,16 @@ SlashCo.LangTable["Watcher_watched"] = "YOU ARE BEING WATCHED"
 SlashCo.LangTable["Watcher_observe"] = "OBSERVING A SURVIVOR. . ."
 SlashCo.LangTable["Watcher_stalktime"] = "STALK TIME: "
 
+--BREN
+SlashCo.LangTable["Bren"] = "BREN"
+SlashCo.LangTable["Bren_desc"] = [[A terrifying Umbra which can phase through solid objects. Extremely aggressive.
+
+-Bren can phase through doors and walls when he's angry.
+-He can increase the fog with a simple snap.
+-This slasher has a very bad eyesight.]]
```
Comment (textstack) [inline lua/slashco/lang/en.lua]: has very bad

File: lua/slashco/perks/faster_fueling.lua
Comment (textstack) [inline lua/slashco/perks/faster_fueling.lua:1]: i feel like it'd be easier to use the item hooks instead of making separate perk hooks

**Review by textstack — COMMENTED** [review]
some things i noticed, also still needs branding (update name/images)

File: gamemodes/slashco/gamemode/sv_player.lua [hunk 20]
```diff
@@ -93,25 +110,39 @@ hook.Add("GetFallDamage", "RealisticDamage", function(_, speed)
...
+		return true
+	end
+
+	local speakerTeam = speaker:Team()
+	if speakerTeam == TEAM_SLASHER then
 		return false
 	end
-	if listener:Team() == TEAM_SLASHER then
+
+	if listenerTeam == TEAM_SLASHER then
```
Comment (textstack) [inline gamemodes/slashco/gamemode/sv_player.lua]: slashers/spectators can hear each other's voice but it seems they cannot see each other's chat

Comment (RaphaelIT7) [reply gamemodes/slashco/gamemode/sv_player.lua]: They shouldn't be able to hear each other's voice:
`if listenerTeam == talkerTeam and (talkerTeam == TEAM_SLASHER or talkerTeam == TEAM_SPECTATOR) then`

File: gamemodes/slashco/entities/entities/sc_beerkeg.lua (hunk 3 above)
Comment (RaphaelIT7) [reply gamemodes/slashco/entities/entities/sc_beerkeg.lua]: iirc while developing I had tried to change gravity there though did it differently in the end.
removed it

File: gamemodes/slashco/entities/entities/sc_activeteslacoil.lua (hunk 2 above)
Comment (RaphaelIT7) [reply gamemodes/slashco/entities/entities/sc_activeteslacoil.lua]: There should now barely be any vector & color creation

File: gamemodes/slashco/gamemode/documents/cl_documents.lua (hunk 9 above)
Comment (RaphaelIT7) [reply gamemodes/slashco/gamemode/documents/cl_documents.lua]: Removed it, it was originally added for #56 though I was never able to reproduce the issue

File: gamemodes/slashco/gamemode/sh_canbeseen.lua (hunk 13 above)
Comment (RaphaelIT7) [reply gamemodes/slashco/gamemode/sh_canbeseen.lua:44]: I left a comment for it now which should make it a bit clearer

File: gamemodes/slashco/gamemode/sv_game_logic.lua (hunk 16 above)
Comment (RaphaelIT7) [reply gamemodes/slashco/gamemode/sv_game_logic.lua]: was supposed to be local xd

File: lua/slashco/perks/faster_fueling.lua
Comment (RaphaelIT7) [reply lua/slashco/perks/faster_fueling.lua:1]: The issue currently is, that I can't just throw the perk value check into ItemValue, as it might for some values, behave wrong / I think it could cause issues in the **future**, which is why I added PerkValue for now to have better control and let ItemValue & PerkValue stack.
But I need to work on perks later again anyways, their still WIP and that is the only perk I've got rn and I want PerkValue to account for all perks and not just return the first one it finds, when I get to that I'd probably be able to also add that into ItemValue later too.

**Comment by RaphaelIT7** [comment]
Should be ready

File: gamemodes/slashco/entities/entities/sc_activeteslacoil.lua [hunk 21]
```diff
@@ -0,0 +1,349 @@
...
+				ply:PlayGlobalSound("slashco/survivor/teslacoil_stun.mp3", 100, 5)
+			end
+		end
+
+		if (curTime - startTime) > 29 and state == 5 then
+			self:SetChargeState(6)
+			for _, slasher in ipairs(team.GetPlayers(TEAM_SLASHER)) do
+				slasher:SetNW2Float("TeslaStunned", curTime + stunTime)
+				slasher:SetNW2Float("LastTeslaStun", curTime)
+				slasher:ScreenFade(SCREENFADE.OUT, Color(0, 0, 0), 0.5, stunTime)
```
Comment (textstack) [inline gamemodes/slashco/entities/entities/sc_activeteslacoil.lua]: could have a `color_black` here

Comment (RaphaelIT7) [reply gamemodes/slashco/entities/entities/sc_activeteslacoil.lua]: Done :)

File: gamemodes/slashco/gamemode/sv_player.lua (hunk 20 above)
Comment (textstack) [reply gamemodes/slashco/gamemode/sv_player.lua]: they should be able to, at least that is what https://github.com/Mantibro/SlashCo/pull/47 was trying to do

Comment (RaphaelIT7) [reply gamemodes/slashco/gamemode/sv_player.lua]: It was talking about Spectator == Spectator and Slasher == Slasher
-> "to those on their team" not across

Comment (textstack) [reply gamemodes/slashco/gamemode/sv_player.lua]: ah yes that was what i meant, sorry for the confusion
i meant that was the case for voice but not text chat

Comment (RaphaelIT7) [reply gamemodes/slashco/gamemode/sv_player.lua]: Should be fixed, though I gotta test it later

**Review by textstack — APPROVED** [review]
still need branding for updating the workshop but the code is good

File: lua/slashco/slasher/tyler.lua [hunk 22]
```diff
@@ -349,6 +349,21 @@ function SLASHER.OnTickBehaviour(slasher)
...
+					minDistance = 15000,
+					maxDistance = 20000,
+					looping = true,
+					entity = slasher,
+					volume = 0.6,
+					fadeIn = 1,
+				})
+			end
+
 			if anger < 50 then -- switch up songs if his anger is below 50.
```
Comment (RaphaelIT7) [inline lua/slashco/slasher/tyler.lua]: @Xerkdot you should probably check here too for `not endlessChase and anger < 50` else both could probably play if they somehow get the helicopter before he's above 50 anger

File: lua/slashco/slasher/covenant_cloak.lua [hunk 23]
```diff
@@ -76,12 +76,22 @@ function SLASHER.OnTickBehaviour(slasher, target)
...
 			slasher.TackledPlayer = nil
+
 			timer.Simple(2.0, function()
 				if not IsValid(slasher) then return end
 
 				slasher:Freeze(false)
 			end)
 		end
+
+		timer.Simple(SLASHER_STUN_TIME, function()
```
Comment (RaphaelIT7) [inline lua/slashco/slasher/covenant_cloak.lua]: You should put this somewhere in `SLASHER.OnPrimaryFire` but not in `SLASHER.OnTickBehaviour` as now you'd spam timers every frame
